version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./Backend:/app
      - /app/models # Preserve the models directory
      - /app/__pycache__
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

networks:
  app-network:
    driver: bridge